;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_putchar
	.export		_main

; ---------------------------------------------------------------
; void __near__ putchar (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_putchar: near

.segment	"CODE"

	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $8800
	jmp     L0009
L0009:	ldx     #$00
	lda     $8801
	ldx     #$00
	and     #$10
	cpx     #$00
	bne     L000E
	cmp     #$00
L000E:	jsr     booleq
	jne     L0009
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jmp     L0012
L0010:	ldx     #$00
	lda     $8806
	cmp     #$00
	jsr     boolne
	jeq     L0012
	lda     #$53
	jsr     pusha
	jsr     _putchar
	lda     #$69
	jsr     pusha
	jsr     _putchar
	lda     #$67
	jsr     pusha
	jsr     _putchar
	lda     #$20
	jsr     pusha
	jsr     _putchar
	lda     #$44
	jsr     pusha
	jsr     _putchar
	lda     #$65
	jsr     pusha
	jsr     _putchar
	lda     #$74
	jsr     pusha
	jsr     _putchar
	lda     #$65
	jsr     pusha
	jsr     _putchar
	lda     #$63
	jsr     pusha
	jsr     _putchar
	lda     #$74
	jsr     pusha
	jsr     _putchar
	lda     #$2E
	jsr     pusha
	jsr     _putchar
	lda     #$20
	jsr     pusha
	jsr     _putchar
L0012:	jmp     L0010
	ldx     #$00
	lda     #$00
	jmp     L000F
L000F:	rts

.endproc

